export type JournalBlock =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'ul'; items: readonly string[] }
  | { type: 'ol'; items: readonly string[] };

export const posts = [
  {
    slug: 'sleep-easy-7-ways-to-get-a-better-nights-rest-naturally',
    title: 'Sleep Easy - 7 ways to get a better nights rest naturally',
    author: 'Holistic Health Hub',
    date: 'Mar 15, 2024',
    dateIso: '2024-03-15T09:00:00+00:00',
    read: '5 min read',
    category: 'Sleep',
    art: 'sleep',
    excerpt: 'Today is World Sleep Day—the annual celebration of healthy sleeping patterns and awareness day for sleep disorders.',
    body: [
      { type: 'p', text: 'Today is World Sleep Day—the annual celebration of healthy sleeping patterns and awareness day for sleep disorders.' },
      { type: 'p', text: 'The NHS state that nearly one in three of us suffer from poor sleep. And the Mental Health Foundation found that nearly (48%) of UK adults agreed that sleeping badly has a negative effect on their mental health.' },
      { type: 'h2', text: 'The significance of adequate sleep' },
      { type: 'p', text: 'Sleep plays a crucial role in maintaining our mental and physical health. While the exact amount of sleep needed can differ from person to person, the general recommendation for most adults is between 7 to 9 hours each night. Individual needs may vary, with some requiring more and others less, but the common thread is the noticeable benefit of waking up feeling revitalised, energised, and prepared for the day. Humans sleep in cycles with each cycle lasting between 90-120 minutes. Once a cycle starts it must finish, otherwise you risk feeling tired and sluggish. Each cycle has different phases including REM sleep (this is where your vivid dreams occur), deep sleep (this is deep restorative sleep) and light sleep (the longest phase of our sleep). Each phase is important as it serves different functions for restoration and rest. A wearable device like a smart watch or ring can help you understand which phases of your cycle you are lacking in and your overall quality per cycle.' },
      { type: 'p', text: 'The negative effects of insufficient sleep are likely familiar to you, impacting numerous facets of our physical and mental well-being. For instance:' },
      { type: 'ul', items: [
        'Physical health: Inadequate sleep can significantly harm our physical health, leading to difficulties in clear thinking, diminished immune function, challenges with weight management, and heightened risks of developing conditions such as high blood pressure, heart disease, and diabetes.',
        'Mental health and well-being: Studies have demonstrated that poor sleep quality can impair our emotional regulation, affect impulse control, reduce positive thinking, increase anxiety, and contribute to or exacerbate depression.',
      ]},
      { type: 'h2', text: 'The consequences of poor sleep' },
      { type: 'ul', items: [
        'Poor sleep can lower immune response, creating greater susceptibility to infections that further reduce sleep quality.',
        'Poor sleep has been linked to obesity, diabetes, coronary artery disease, and cardiovascular mortality.',
        'Certain sleep disorders like obstructive sleep apnoea and rapid eye movement sleep behaviour disorder are associated with cognitive impairment, dementia, risk of seizures, and increased risk of stroke.',
        'Poor sleep can result in reduced reaction times, impaired judgment, and cognitive impairment similar in effect to alcohol intoxication.',
        'Drowsiness can impair safe driving even if the driver does not fall asleep.',
      ]},
      { type: 'h2', text: '7 ways to naturally improve sleep' },
      { type: 'h2', text: '1. Have a good sleep routine (sleep hygiene)' },
      { type: 'p', text: 'Having a regular routine helps to improve sleep. It\'s sometimes called sleep hygiene. A good sleep routine should include having a set time to start winding down – and a way to relax is important too. Going to bed and getting up at fixed times is another good sleep habit. Ideally, a sleep routine should be the same every day, including weekends.' },
      { type: 'h2', text: '2. Relax, unwind and try meditation to help you sleep' },
      { type: 'p', text: 'Remember, your sleep routine starts before you get into bed, so build in time every evening to relax. Avoid electronic devices at least an hour before bed, as mobiles, tablets and computers all throw out blue light that stops sleep. Activate airplane mode to avoid any distractions. Reading, listening to soft music or a podcast, or sleep meditation can all help if you have trouble sleeping. Meditation has been shown to slow brain waves down which prepares your body for sleep.' },
      { type: 'h2', text: '3. Try mindfulness for sleep' },
      { type: 'p', text: 'Anxiety, worry and stress can affect how well we sleep. Luckily, there are things you can do daily to help manage your worries, like talking to someone you trust or writing in a notebook about your concerns. If you often lie awake worrying, set aside time before bed to make a to-do list for the next day – this can be a good way to put your mind at rest.' },
      { type: 'h2', text: '4. Create the right sleep environment' },
      { type: 'p', text: 'It\'s generally easier to drop off when it\'s quiet, dark and cool – although the right sleep environment is personal, so try different things and see what works for you. Silence is golden when it comes to sleep for many of us, so wearing earplugs, putting your phone on silent (or out of the room entirely) can keep things quiet. Good curtains or blinds can help to keep a room dark and avoid unwanted lights by keeping clocks out of view and phones facing down. Make sure your room is the right temperature for you and well ventilated, as a cool room is usually better to sleep in than a hot or stuffy one. Some people also find it helps to play music for sleep, such as ambient sounds like rainfall, gentle music or white noise.' },
      { type: 'h2', text: '5. Do not force sleep' },
      { type: 'p', text: 'If you\'re lying awake unable to sleep, do not try to force it. If you\'re tired and enjoying the feeling of resting, then sleep may naturally take over. But if you cannot sleep, get up and sit in a comfy place and do something relaxing, like reading a book or listening to quiet music. Only go back to bed when you feel sleepier.' },
      { type: 'h2', text: '6. Improve sleep through diet and exercise' },
      { type: 'p', text: 'A good diet and regular physical exercise can help us to relax and get better sleep. And the opposite is also true: an unhealthy diet and lack of exercise can stop us from sleeping well. Avoid eating large meals close to bedtime. Try to also ditch the bedtime caffeine (like coffee), alcohol or nicotine if you can, because these are stimulants that make us more alert. Stimulants are a common cause of sleep problems. The general advice is to avoid stimulants 1 to 2 hours before bed. Try it and see if things improve. Regular exercise helps with sleep, but avoid anything too energetic in the 90 minutes before bedtime if you find it stops you from sleeping.' },
      { type: 'h2', text: '7. Natural sleep aids' },
      { type: 'p', text: 'Even if the above are strictly followed, sometimes we need an extra hand. Valerian root has been shown to help promote sleep in those suffering with mild insomnia. Medical cannabis can help with sleep by interacting with the body\'s endocannabinoid system to promote relaxation and reduce anxiety, making it easier to fall asleep and potentially improve the quality of sleep. Magnesium plays a key role in supporting deep, restorative sleep by regulating brain chemicals that the mind and nervous system preparing the body for sleep. Foods high in magnesium include dark leafy greens (such as spinach and Swiss chard), nuts and seeds (like almonds, pumpkin seeds and chia seeds), whole grains (such as rice and quinoa), legumes (like black beans and lentils), and dark chocolate. Magnesium can also be supplemented in the form of capsules and tablets.' },
      { type: 'p', text: 'Sleep is vital to our health and getting better quality sleep is essential to our bodies running optimally. There are many ways to improve sleep and identifying some areas you can improve on could lead to the biggest positive changes in how you feel.' },
      { type: 'p', text: 'Take a step towards improving your sleep and watch as other areas of your health improve.' },
    ],
  },
  {
    slug: 'cannabis-for-anxiety-what-you-need-to-know',
    title: 'Medical Cannabis for Anxiety: What You Need to Know',
    author: 'Holistic Health Hub',
    date: 'Feb 14, 2024',
    dateIso: '2024-02-14T09:00:00+00:00',
    read: '5 min read',
    category: 'Mental wellbeing',
    art: 'anxiety',
    excerpt: 'In today’s fast-paced world, anxiety has emerged as a silent shadow, affecting millions globally.',
    body: [
      { type: 'h2', text: 'Introduction' },
      { type: 'p', text: 'In today\'s fast-paced world, anxiety has emerged as a silent shadow, affecting millions globally. It\'s a condition that not only disrupts daily functioning but also deeply impacts the quality of life. Amidst a myriad of treatment options, medical cannabis offers a new approach to managing anxiety symptoms.' },
      { type: 'p', text: 'Anxiety is the main symptom of several conditions including:' },
      { type: 'ul', items: [
        'Panic disorder',
        'Phobias, such as agoraphobia or claustrophobia',
        'PTSD',
        'Social anxiety disorder',
      ]},
      { type: 'p', text: 'Generalised Anxiety Disorder (GAD) is a persistent condition leading to widespread anxiety over various situations, not just one event. Those with GAD frequently feel anxious, finding it hard to recall when they last felt at ease.' },
      { type: 'p', text: 'Traditional treatments include therapy, medicine such as antidepressants, and lifestyle adjustments, but not everyone finds relief through these avenues.' },
      { type: 'p', text: 'This article is designed to provide a comprehensive overview, empowering you with the information needed to make informed decisions about managing anxiety with medical cannabis.' },
      { type: 'h2', text: 'What is medical cannabis?' },
      { type: 'p', text: 'Cannabis-based products for medicinal use (CBPM) or simply medical cannabis, refers to the use of cannabis and its various chemicals called cannabinoids, as medical therapy to treat disease or alleviate symptoms. Cannabis has been used for medicinal purposes for thousands of years, but its therapeutic use has seen a resurgence in recent years, thanks to a growing body of research and changing societal attitudes.' },
      { type: 'p', text: 'At the heart of medical cannabis are two primary cannabinoids: Tetrahydrocannabinol (THC) and Cannabidiol (CBD). THC is the psychoactive component that produces the "high" associated with recreational cannabis use and may positively or negatively impact mood depending on how it’s used. In contrast, CBD does not produce this psychoactive effect and is often highlighted for its potential therapeutic benefits, including anxiety reduction. These cannabinoids work by activating the endocannabinoid system.' },
      { type: 'h2', text: 'The science behind cannabis and anxiety' },
      { type: 'p', text: 'The relationship between cannabis and anxiety is complex and involves the body\'s endocannabinoid system (ECS), which plays a significant role in regulating vital bodily functions such as mood, appetite, sleep and pain perception. The ECS is partly made up of cannabinoid receptors (CB1 and CB2) which are activated by cannabinoids like THC and CBD.' },
      { type: 'h2', text: 'Cannabinoid receptors and anxiety' },
      { type: 'h2', text: 'CB1 receptors' },
      { type: 'p', text: 'Primarily located in the brain and central nervous system, they play a key role in reducing fear and anxiety. The activation of CB1 receptors by endocannabinoids can influence mood in several ways:' },
      { type: 'ul', items: [
        'Neurotransmitter release: CB1 receptors regulate the release of various neurotransmitters (natural brain chemicals), including serotonin, dopamine, and glutamate, which are crucial for mood balance.',
        'Stress response: CB1 receptor activation can reduce the release of stress hormones.',
        'Neuroplasticity: The CB1 receptor plays a role in neuroplasticity – the brain\'s ability to reorganise itself by forming new connections. This process is essential for mood regulation, learning, and memory. Dysregulation of this system is associated with various mood disorders.',
      ]},
      { type: 'h2', text: 'CB2 receptors' },
      { type: 'p', text: 'The role of CB2 receptors in mood regulation is less direct than that of CB1 receptors but is increasingly recognised as significant, particularly in the context of neuroinflammation and neurodegenerative diseases:' },
      { type: 'ul', items: [
        'Neuroinflammation: CB2 receptor activation can reduce inflammation in the brain, which is associated with mood disorders such as anxiety and depression.',
        'Stress response: There is evidence to suggest that CB2 receptors may influence the stress response indirectly. By reducing inflammation, CB2 receptor activation could potentially prevent the negative effects of chronic stress on the brain and mood.',
      ]},
      { type: 'p', text: 'Studies have shown that CBD has potential therapeutic effects on anxiety without the psychoactive effects associated with THC. It also contributes to reducing the psychoactive effects of THC which means if taken together you are less likely to \'get high\'.' },
      { type: 'p', text: 'However, some research suggests that low to moderate doses of THC can reduce anxiety, while higher doses may exacerbate it.' },
      { type: 'p', text: 'It is important to note that individual responses to cannabis can vary significantly, influenced by genetic factors, specific anxiety disorders, the dose and formulation of medical cannabis used.' },
      { type: 'h2', text: 'Using medical cannabis for anxiety: methods and dosage' },
      { type: 'h2', text: 'Methods of consumption' },
      { type: 'p', text: 'The method of consuming medical cannabis can significantly affect its effectiveness and how quickly it works. Common methods include:' },
      { type: 'ul', items: [
        'Inhalation (by dried herb vaping): Offers rapid relief as the cannabinoids enter the bloodstream directly through the lungs but effects do not last long. This method may be used as and when required when symptoms get worse.',
        'Capsules: Provide longer-lasting effects but have a delayed onset time because the cannabinoids are absorbed through the digestive system which may take some time. However dosage control can be challenging with capsules as much of the cannabinoids are not absorbed by the body through this route.',
        'Oils and tinctures: Administered under the tongue, they offer a balance between relatively quick onset and ease of dose control, making them a preferred choice for medical use.',
      ]},
      { type: 'h2', text: 'Dosage considerations' },
      { type: 'p', text: 'Determining the right dosage is crucial and can vary widely among individuals. Key guidelines include:' },
      { type: 'ul', items: [
        'Start low and go slow: Begin with a low dose, especially if THC is present, and gradually increase until you find the most effective dose with the fewest side effects.',
        'Consult healthcare professionals: It\'s essential to work with a healthcare professional experienced in medical cannabis to tailor the dosage to your specific needs.',
        'Monitor effects: Keep a journal to track the dosage, method of consumption, and effects on anxiety symptoms to help fine-tune your regimen. Your healthcare professional can assist you with this.',
      ]},
      { type: 'h2', text: 'What the journey with medical cannabis for anxiety is like' },
      { type: 'p', text: 'It is legal to use medical cannabis for anxiety, that is prescribed by a specialist doctor.' },
      { type: 'p', text: 'Where appropriate, starting medical cannabis treatment typically involves:' },
      { type: 'ol', items: [
        'An eligibility assessment which determines if an appointment with a specialist is suitable.',
        'An appointment consists of a 30 min consultation with a specialist doctor who will assess you and listen to your history with anxiety and address any concerns you may have.',
        'Your case will be checked and reviewed by a multidisciplinary team of specialist doctors who will determine whether medical cannabis is suitable for you.',
        'If appropriate they will create a personalised treatment plan and issue you with a prescription which may be dispensed at your nominated pharmacy.',
        'You will be continuously monitored by the clinic and your pharmacy to ensure the treatment is safe and effective.',
        'Regular follow ups with your specialist can ensure your treatment is optimised to your needs.',
      ]},
      { type: 'p', text: 'In addition to your personalised medical cannabis treatment plan your healthcare team consisting of specialist doctors, pharmacists and nurses may also recommend other forms of treatment that may help with your condition.' },
      { type: 'p', text: 'Understanding the methods, dosage, benefits, and potential side effects of medical cannabis is crucial for anyone considering it as a treatment option for anxiety. With careful consideration and guidance from healthcare professionals, medical cannabis may offer a valuable alternative for managing anxiety symptoms, improving quality of life for those affected by this condition.' },
      { type: 'p', text: 'If you would like to check your eligibility for referral to a specialist clinic, complete the secure eligibility check with Holistic Health Hub.' },
      { type: 'h2', text: 'References' },
      { type: 'ul', items: [
        'Sarris, J., Sinclair, J., Karamacoska, D., Davidson, M., & Firth, J. (2020). Medicinal cannabis for psychiatric disorders: a clinically-focused systematic review. BMC Psychiatry, 20(1).',
        'Ergisi, M., Erridge, S., Harris, M., Kawka, M., Nimalan, D., Salazar, O., Loupasaki, K., Ali, R., Holvey, C., Coomber, R., Platt, M., Rucker, J., & Sodergren, M. H. (2022). UK Medical Cannabis Registry: an analysis of clinical outcomes of medicinal cannabis therapy for generalized anxiety disorder. Expert Review of Clinical Pharmacology, 1–9.',
        'Berger, M., Amminger, G. P., & McGregor, I. S. (2022). Medicinal cannabis for the treatment of anxiety disorders. Australian Journal of General Practice, 51(8), 586–592.',
        'Rifkin-Zybutz, R., Erridge, S., Holvey, C., Coomber, R., Gaffney, J., Lawn, W., Barros, D., Bhoskar, U., Mwimba, G., Praveen, K., Symeon, C., Sachdeva-Mohan, S., Rucker, J. J., & Sodergren, M. H. (2023). Clinical outcome data of anxiety patients treated with cannabis-based medicinal products in the United Kingdom: a cohort study from the UK Medical Cannabis Registry. Psychopharmacology.',
        'Won, E., & Kim, Y.-K. (2020). Neuroinflammation-Associated Alterations of the Brain as Potential Neural Biomarkers in Anxiety Disorders. International Journal of Molecular Sciences, 21(18), 6546.',
        'Stachowicz, K. (2023). Deciphering the mechanisms of reciprocal regulation or interdependence at the cannabinoid CB1 receptors and cyclooxygenase-2 level: Effects on mood, cognitive implications, and synaptic signaling. Neuroscience & Biobehavioral Reviews, 155, 105439.',
        'NHS website. Overview - Generalised anxiety disorder in adults. nhs.uk.',
      ]},
    ],
  },
  {
    slug: 'navigating-pain-relief-the-role-of-medical-cannabis-in-chronic-pain-management',
    title: 'Navigating Pain Relief: The Role of Medical Cannabis in Chronic Pain Management',
    author: 'Shaylen Patel',
    date: 'Jan 31, 2024',
    dateIso: '2024-01-31T09:00:00+00:00',
    read: '3 min read',
    category: 'Pain',
    art: 'pain',
    excerpt: 'Chronic pain represents a profound challenge in healthcare, persisting far beyond the expected period of healing.',
    body: [
      { type: 'h2', text: 'Introduction' },
      { type: 'p', text: 'Chronic pain represents a profound challenge in healthcare, persisting far beyond the expected period of healing. Traditional remedies and advancements in medicine have continuously sought to alleviate this issue. Remarkably, medical cannabis emerges as a modern solution, echoing its historical use for pain relief, including by figures such as Queen Victoria who was frequently prescribed medical cannabis for period pains. This article explores the resurgence of medical cannabis in pain management, underpinned by modern research and clinical practices.' },
      { type: 'h2', text: 'Understanding chronic pain' },
      { type: 'p', text: 'Chronic pain is a complex and persistent condition, often difficult to manage due to its multifaceted nature involving psychological, physical, and environmental factors. Defined as pain lasting longer than three months, it not only persists but can also trigger or worsen conditions like depression, anxiety, and sleep disturbances, significantly impacting quality of life. Often, the origin lurks not in tissue damage, but in altered pain processing pathways. This is caused by changes in the nervous system that make it more sensitive to pain signals.' },
      { type: 'h2', text: 'Managing chronic pain: a multidisciplinary approach' },
      { type: 'p', text: 'Management and treatment of chronic pain often requires a multifaceted approach, tailored to individual needs. Medicines like NSAIDs and opioids offer relief, while antidepressants can target underlying mood disorders. Physical therapy aids in restoring function, and cognitive-behavioural therapy (CBT) addresses psychological impacts. Lifestyle modifications can also improve overall well-being. However, sometimes these options are not enough and can also cause unwanted side effects. For example the long-term use of opioids such as codeine and morphine are not recommended for long-term pain relief because there is little evidence to support it and there is a risk of addiction and overdose.' },
      { type: 'h2', text: 'The potential of medical cannabis in pain relief' },
      { type: 'p', text: 'Cannabis has gained attention for its potential in treating a wide array of chronic pain conditions, from neuropathic pain, cancer pain, fibromyalgia, complex-regional pain syndrome, rheumatoid arthritis, and chemotherapy-induced pain to name a few. The therapeutic properties of cannabis are attributed to its key components, THC and CBD, which offer pain-relieving and anti-inflammatory effects, respectively. The balance between THC and CBD plays a pivotal role in tailoring treatment to individual needs, minimising side effects while maximising relief. Studies have shown medical cannabis can improve symptoms of pain, improve quality of life and lead to reduction in usage and reliance on opioid based medicines.' },
      { type: 'h2', text: 'How medical cannabis works to relieve pain' },
      { type: 'p', text: 'The effectiveness of medical cannabis in pain management is largely due to its interaction with the body’s endocannabinoid system. This system regulates various bodily processes, including pain sensation, mood, appetite, and memory. By influencing this system, cannabis can alter the perception of pain. The anti-inflammatory properties of medical cannabis are another crucial aspect of its pain-relieving effects. By reducing inflammation, cannabis can alleviate pain associated with various conditions, including neuropathic pain and cancer-associated pain providing relief where traditional medicines may be inadequate.' },
      { type: 'h2', text: 'Administering medical cannabis for pain' },
      { type: 'p', text: 'The administration of medical cannabis has evolved, with a range of methods suited to different types of pain and patient preferences. Dried herb vaporisers, for example, offer a quick-acting solution without the harmful by-products of smoking. Meanwhile, oils and capsules provide longer-lasting effects and convenience for sustained pain management. These methods offer safe ways to administer medical cannabis, whilst providing dosing control, which can help limit the side effects.' },
      { type: 'h2', text: 'Consulting healthcare professionals' },
      { type: 'p', text: 'For those considering medical cannabis for pain relief, the first step is an informed discussion with healthcare professionals. This ensures a thorough understanding of its benefits and risks, including potential interactions with existing medicines. As evidence supporting medical cannabis grows, it offers a promising alternative or add-on therapy to traditional pain management strategies.' },
      { type: 'p', text: 'Medical cannabis represents a significant development in the ongoing quest to manage chronic pain. With its historical roots and modern scientific backing, it provides a new approach that requires careful consideration and guidance from trained healthcare professionals.' },
      { type: 'h2', text: 'References' },
      { type: 'ul', items: [
        'Sunderland P, Nutt DJ, Schlag AK. Medication sparing after medical cannabis initiation: A case study of a chronic pain patient in Project Twenty21. Drug Science, Policy and Law. 2023;9.',
        'McMahon, A. et al. (2023) Perceived effectiveness of medical cannabis among adults with chronic pain: Findings from interview data in a three-month pilot study, Cannabis.',
        'Lara Bapir, Simon Erridge, Martha Nicholas, Manaswini Pillai, Nishaanth Dalavaye, Carl Holvey, Ross Coomber, Jonathan Hoare, Shaheen Khan, Mark W Weatherall, James J Rucker, Michael Platt & Mikael H Sodergren (2023) Comparing the effects of medical cannabis for chronic pain patients with and without co-morbid anxiety: A cohort study, Expert Review of Neurotherapeutics, 23:3, 281-295.',
      ]},
    ],
  },
  {
    slug: 'the-endocannabinoid-system-bringing-your-body-back-to-balance',
    title: 'The Endocannabinoid System: Bringing your body back to balance',
    author: 'Shaylen Patel',
    date: 'Jan 26, 2024',
    dateIso: '2024-01-26T09:00:00+00:00',
    read: '2 min read',
    category: 'CBPM 101',
    art: 'balance',
    excerpt: 'The endocannabinoid system is a complex cell-signalling system involved in establishing and maintaining balance.',
    body: [
      { type: 'h2', text: 'What is the endocannabinoid system (ECS)?' },
      { type: 'p', text: 'The ECS is a complex cell-signalling system, involved in establishing and maintaining health. Discovered while researching THC, a well-known component in cannabis, the ECS is essential in maintaining the delicate balance within our internal environment.' },
      { type: 'p', text: 'Active irrespective of cannabis use, the ECS comprises endocannabinoids, receptors, and enzymes. This trio functions like an internal regulator, ensuring that various bodily functions operate smoothly and stay balanced.' },
      { type: 'p', text: 'Endocannabinoids are molecules made by your body, mirroring compounds found in cannabis but naturally produced. Think of them as keys that fit into locks leading to activation of a series of processes resulting in internal balance. This is called homeostasis.' },
      { type: 'p', text: 'The primary endocannabinoids are anandamide (AEA) and 2-arachidonoylglycerol (2-AG). These molecules are crucial for keeping internal functions on track, produced on-demand by your body. Anandamide is named after the Sanskrit word ‘Ananda’ which translates to ‘bliss’. Yes, your body produces bliss molecules, but sometimes, not enough of it!' },
      { type: 'h2', text: 'What are receptors?' },
      { type: 'p', text: 'Think of ECS receptors as the locks that are activated by the keys (endocannabinoids). These locks are found throughout your body and there are 2 main types:' },
      { type: 'ul', items: [
        'CB1 receptors are mainly in the central nervous system.',
        'CB2 receptors in the peripheral nervous system, particularly in immune cells.',
      ]},
      { type: 'p', text: 'Endocannabinoids interact with these receptors, initiating actions needed to maintain balance. The effect depends on the receptor\'s location and the specific endocannabinoid it binds to.' },
      { type: 'p', text: 'The ECS is present throughout the whole body and is involved in key bodily functions.' },
      { type: 'h2', text: 'What are enzymes?' },
      { type: 'p', text: 'Enzymes in the ECS break down endocannabinoids once they\'ve served their purpose. These enzymes ensure that endocannabinoids are used as needed, without lingering longer than necessary.' },
      { type: 'p', text: 'The primary objective of the ECS is to maintain homeostasis. The ECS is intricately linked to several key bodily processes. It acts as the internal regulator, constantly fine-tuning various bodily functions to adapt to changes and maintain a stable internal environment. It plays a part in:' },
      { type: 'ul', items: [
        'Appetite and digestion',
        'Metabolism',
        'Pain perception',
        'Inflammation and immune responses',
        'Mood, learning, and memory',
        'Motor control (movement)',
        'Sleep',
        'Cardiovascular system function',
        'Bone formation',
        'Liver function',
        'Reproductive system function',
        'Stress responses',
        'Skin health',
      ]},
      { type: 'p', text: 'Each of these functions is critical to maintaining homeostasis, the stable and optimal operation of your internal world. If external factors disrupt this balance, the ECS steps in to help your body adapt and return to equilibrium.' },
      { type: 'p', text: 'Understanding the ECS and its role as the internal regulator of our bodies offers valuable insights into health and well-being. It highlights the intricate mechanisms our bodies use to maintain balance and adapt to internal and external changes.' },
      { type: 'p', text: 'Dysfunction of the ECS could lead to a variety of health conditions. The good news is your endocannabinoid system can be enhanced in many ways including exercise, avoiding alcohol, meditating and CBPM (medical cannabis) therapy.' },
    ],
  },
] as const;
