import type {
  CRMPatient,
  LineItem,
  PatientOrder,
  PharmacyTenant,
  Prescription,
  PrescriptionFulfilmentLine,
} from '../context/AppContext';
import type { CuraleafQuote, PortalOrderRecord } from '../shared/contracts';

export const TRAINING_REFERRAL_SOURCE = 'training_sandbox';

export const TRAINING_PRODUCT = {
  id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
  formulaId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2',
  name: 'Training flower 10g',
  packSize: 10,
  retail: 85,
  cost: 42,
  supplierState: 'ACTIVE',
} as const;

export const TRAINING_PRESCRIBER = {
  id: 'training-prescriber',
  name: 'Dr Training Clinic',
  gmcNumber: '7000001',
} as const;

export const ORGANISATIONS: PharmacyTenant[] = [
  {
    id: '3e9f74ff-4fed-497d-904d-4d3ee3e5e126',
    slug: 'primary-branch',
    referralToken: 'primary-branch-7x4p9k',
    name: 'Primary Branch',
    tradingName: 'Primary Branch',
    logoText: 'PB',
    gphcNumber: '1099224',
    superintendent: 'Shaylen Patel',
    companyNumber: '1099224',
    mainContactName: 'Shaylen Patel',
    mainContactPhone: '0113 000 0000',
    mainContactEmail: 'pharmacy@primarybranch.cc',
    curaleafPharmacyCode: '109c6bca-585a-4b69-b6bb-072e0731dd10',
    address: 'Leeds, West Yorkshire, United Kingdom',
    websiteDomains: ['primarybranch.cc'],
    status: 'onboarding',
    staffCount: 4,
    defaultPaymentRoute: 'manual',
    brand: { primary: '#0f766e', portalName: 'Primary Branch' },
    worldpay: { enabled: false, status: 'not-connected', environment: 'sandbox', merchantId: null, merchantName: null, lastSyncedAt: null },
  },
  {
    id: '6d0176bb-89a0-4e32-9bce-c934c9557c42',
    slug: 'eastwood-health-pharmacy',
    referralToken: 'eastwood-3m8q2v',
    name: 'Eastwood Health Pharmacy',
    tradingName: 'Eastwood Health Ltd',
    logoText: 'EH',
    gphcNumber: '9012726',
    superintendent: 'Shaylen Patel',
    companyNumber: '9012726',
    mainContactName: 'Shaylen Patel',
    mainContactPhone: '01522 000 000',
    mainContactEmail: 'contact@eastwoodhealthpharmacy.cc',
    curaleafPharmacyCode: '04568c82-b3d2-4082-9277-3313b48d10f4',
    address: 'Nottinghamshire, United Kingdom',
    websiteDomains: ['eastwoodhealthpharmacy.cc'],
    status: 'live',
    staffCount: 2,
    defaultPaymentRoute: 'manual',
    brand: { primary: '#1e40af', portalName: 'Eastwood Health Pharmacy' },
    worldpay: { enabled: false, status: 'not-connected', environment: 'sandbox', merchantId: null, merchantName: null, lastSyncedAt: null },
  },
];

export function isTrainingSandboxPatient(patient: Pick<CRMPatient, 'referralSource' | 'id'>): boolean {
  return patient.referralSource === TRAINING_REFERRAL_SOURCE || patient.id.startsWith('training-');
}

/** Pharmacy staff only have two workspaces: Live (real referred patients) or Training (examples). */
export function resolvePharmacyWorkspaceMode(organisation: Pick<PharmacyTenant, 'status' | 'workspaceClassification' | 'testAccount'> | null | undefined): 'live' | 'training' {
  if (!organisation) return 'training';
  if (organisation.workspaceClassification === 'allocation_holding') return 'live';
  if (organisation.workspaceClassification === 'training' || organisation.testAccount) return 'training';
  if (organisation.status === 'live' || organisation.status === 'paused') return 'live';
  return 'training';
}

export function trainingWorkspace(organisationId: string): {
  crm: CRMPatient[];
  orders: PatientOrder[];
  nextIds: { patient: number; rx: number; order: number; submission: number; invoice: number };
} {
  const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000);
  const isoDay = (days: number) => daysAgo(days).toISOString().slice(0, 10);
  const pack: LineItem = {
    productId: TRAINING_PRODUCT.id,
    formulaId: TRAINING_PRODUCT.formulaId,
    name: TRAINING_PRODUCT.name,
    qty: 1,
    unitsNeededCount: TRAINING_PRODUCT.packSize,
    cost: TRAINING_PRODUCT.cost,
    retail: TRAINING_PRODUCT.retail,
  };
  const twoPacks: LineItem = {
    ...pack,
    qty: 2,
    unitsNeededCount: TRAINING_PRODUCT.packSize * 2,
    cost: TRAINING_PRODUCT.cost * 2,
    retail: TRAINING_PRODUCT.retail * 2,
  };
  const amount = TRAINING_PRODUCT.retail;
  const raisedAmount = 95;
  const splitAmount = TRAINING_PRODUCT.retail * 2;

  const person = (
    slug: string,
    name: string,
    mobile: string,
    dob: string,
    postcode: string,
    condition: string,
    status: CRMPatient['status'],
  ): CRMPatient => ({
    id: `training-${organisationId}-${slug}`,
    organisationId,
    name,
    email: `${slug.replaceAll('-', '.')}@invalid.example`,
    mobile,
    dob,
    postcode,
    conditions: [condition],
    primaryCondition: condition,
    referralSource: TRAINING_REFERRAL_SOURCE,
    status,
  });

  const patients: CRMPatient[] = [
    person('casey', 'Casey Reed', '00000 000 001', '1991-04-12', 'XX0 0AA', 'Chronic pain', 'Referred'),
    person('jamie', 'Jamie Cole', '00000 000 002', '1986-09-03', 'XX0 0BB', 'Anxiety', 'HHH approved'),
    person('morgan', 'Morgan Blake', '00000 000 003', '1978-01-22', 'XX0 0CC', 'Chronic pain', 'HHH approved'),
    person('riley', 'Riley Shah', '00000 000 004', '1994-11-18', 'XX0 0DD', 'Insomnia', 'HHH approved'),
    person('avery', 'Avery Quinn', '00000 000 005', '1983-06-09', 'XX0 0EE', 'Chronic pain', 'HHH approved'),
    person('taylor', 'Taylor West', '00000 000 006', '1975-02-28', 'XX0 0FF', 'MS', 'HHH approved'),
    person('rowan', 'Rowan Hale', '00000 000 007', '1988-07-14', 'XX0 0GG', 'Chronic pain', 'HHH approved'),
    person('drew', 'Drew Patel', '00000 000 008', '1972-03-05', 'XX0 0HH', 'Anxiety', 'HHH approved'),
    person('sage', 'Sage Nguyen', '00000 000 009', '1990-12-01', 'XX0 0JJ', 'Insomnia', 'HHH approved'),
    person('quinn', 'Quinn Fraser', '00000 000 010', '1981-08-19', 'XX0 0KK', 'Chronic pain', 'HHH approved'),
    person('blair', 'Blair Ortiz', '00000 000 011', '1977-05-27', 'XX0 0LL', 'MS', 'HHH approved'),
    person('harper', 'Harper Lane', '00000 000 012', '1993-10-08', 'XX0 0MM', 'Anxiety', 'HHH approved'),
    person('ellis', 'Ellis Brook', '00000 000 013', '1984-01-30', 'XX0 0NN', 'Chronic pain', 'HHH approved'),
    person('indie', 'Indie Walsh', '00000 000 014', '1979-09-16', 'XX0 0PP', 'Insomnia', 'HHH approved'),
    person('marlow', 'Marlow Chen', '00000 000 015', '1987-06-21', 'XX0 0QQ', 'Chronic pain', 'HHH approved'),
    person('shiloh', 'Shiloh Grant', '00000 000 016', '1992-02-11', 'XX0 0RR', 'Anxiety', 'HHH approved'),
    person('jules', 'Jules Hart', '00000 000 017', '1974-11-04', 'XX0 0SS', 'MS', 'HHH approved'),
    person('cameron', 'Cameron Shaw', '00000 000 018', '1985-04-09', 'XX0 0TT', 'Chronic pain', 'HHH approved'),
    person('dana', 'Dana Frost', '00000 000 019', '1989-08-23', 'XX0 0UU', 'Anxiety', 'HHH approved'),
    person('robin', 'Robin Vale', '00000 000 020', '1976-12-15', 'XX0 0VV', 'Insomnia', 'HHH approved'),
    person('finley', 'Finley Moss', '00000 000 021', '1982-07-02', 'XX0 0WW', 'Chronic pain', 'HHH approved'),
    person('kai', 'Kai Bell', '00000 000 022', '1971-03-18', 'XX0 0XX', 'MS', 'HHH approved'),
    person('skyler', 'Skyler Dean', '00000 000 023', '1995-05-06', 'XX0 0YY', 'Anxiety', 'HHH approved'),
    person('peyton', 'Peyton Moss', '00000 000 024', '1980-09-29', 'XX0 0ZZ', 'Chronic pain', 'HHH approved'),
  ];

  const clinicRx = (id: number, status: Prescription['status'], extras: Partial<Prescription> = {}): Prescription => ({
    id,
    entryMode: 'clinic',
    clinicScanId: `training-scan-${id}`,
    curaleafPrescriptionId: `training-prescription-${id}`,
    curaleafPrescriptionState: extras.placed ? 'FULFILLED' : 'PENDING',
    curaleafPatientName: extras.curaleafPatientName,
    curaleafPatientDob: extras.curaleafPatientDob,
    prescriber: TRAINING_PRESCRIBER.name,
    prescriberId: TRAINING_PRESCRIBER.id,
    prescriberGmcNumber: TRAINING_PRESCRIBER.gmcNumber,
    serialNumber: `TRAINING-${isoDay(extras.placed ? 4 : 1).replaceAll('-', '')}-${id}`,
    issueDate: isoDay(extras.placed ? 4 : 1),
    expiryDate: isoDay(extras.placed ? -24 : -27),
    copyFileName: 'training-clinic-copy.pdf',
    items: [pack],
    placed: false,
    poRef: null,
    status,
    invoiceRef: null,
    trackingNumber: null,
    carrier: null,
    ...extras,
  });

  const bySlug = Object.fromEntries(patients.map(patient => [patient.id.split('-').at(-1)!, patient]));
  const line = (partial: Partial<PrescriptionFulfilmentLine> & Pick<PrescriptionFulfilmentLine, 'ordered' | 'allocated' | 'shipped' | 'received' | 'collected'>): PrescriptionFulfilmentLine => ({
    productId: TRAINING_PRODUCT.id,
    requested: partial.ordered,
    sent: partial.shipped,
    supplierReportedOrdered: partial.ordered,
    remaining: Math.max(0, partial.ordered - Math.max(partial.shipped, partial.allocated)),
    returned: 0,
    backordered: false,
    quantityMismatch: false,
    ...partial,
  });
  const paid = (id: number, days: number, notes: string, total = amount, tender: PatientOrder['payment']['manualTender'] = 'epos-card'): PatientOrder['payment'] => ({
    status: 'paid',
    route: 'pharmacy',
    amount: total,
    ref: `TILL-TRAINING-${id}`,
    sentAt: daysAgo(days),
    paidAt: daysAgo(days),
    manualTender: tender,
    manualReference: `TILL-TRAINING-${id}`,
    manualNotes: notes,
    manualRecordedBy: 'Training workspace',
  });
  const orderShell = (id: number, slug: string, days: number, payment: PatientOrder['payment'], prescriptions: Prescription[], extras: Partial<PatientOrder> = {}): PatientOrder => ({
    id,
    backendId: `training-order-${id}`,
    organisationId,
    patientId: bySlug[slug].id,
    date: daysAgo(days),
    dispensingFee: 0,
    paymentRoute: 'manual',
    payment,
    prescriptions,
    ...extras,
  });
  const quote = (patientPackPrice: string, wholesalePackPrice: string, inStock = true): CuraleafQuote => ({
    shippingPrice: '0.00',
    taxRate: '0',
    items: [{
      packId: TRAINING_PRODUCT.id,
      quantity: 1,
      inStock,
      stockStatus: inStock ? 'in_stock' : 'out_of_stock',
      wholesalePackPrice,
      patientPackPrice,
    }],
  });
  const review = (
    status: NonNullable<PortalOrderRecord['quoteReview']>['status'],
    type: NonNullable<PortalOrderRecord['quoteReview']>['type'],
    differences: NonNullable<PortalOrderRecord['quoteReview']>['differences'],
    latestQuote: CuraleafQuote,
    extras: Partial<NonNullable<PortalOrderRecord['quoteReview']>> = {},
  ): NonNullable<PortalOrderRecord['quoteReview']> => ({
    status,
    type,
    fingerprint: `training-${type}-${status}`,
    latestQuote,
    differences,
    checkedAt: daysAgo(1).toISOString(),
    ...extras,
  });
  const namedRx = (id: number, slug: string, status: Prescription['status'], extras: Partial<Prescription> = {}) => clinicRx(id, status, {
    curaleafPatientName: bySlug[slug].name,
    curaleafPatientDob: bySlug[slug].dob,
    ...extras,
  });
  const cancelledRx = (id: number, slug: string, extras: Partial<Prescription> = {}) => namedRx(id, slug, 'cancelled', {
    placed: true,
    placedAt: daysAgo(6),
    poRef: `PO-TRAINING-${id}`,
    purchaseOrderState: 'CANCELLED',
    curaleafPrescriptionId: undefined,
    curaleafPrescriptionState: 'CANCELLED',
    ...extras,
  });
  const replacement = (
    id: number,
    sourceId: number,
    slug: string,
    days: number,
    payment: PatientOrder['payment'],
    extras: Partial<PatientOrder> = {},
    item: LineItem = pack,
  ) => {
    const { redoContext: redoExtras, ...rest } = extras;
    return orderShell(id, slug, days, payment, [namedRx(id * 10 + 1, slug, 'awaiting-approval', { items: [item] })], {
      redoContext: {
        originalOrderId: sourceId,
        originalBackendId: `training-order-${sourceId}`,
        rootOrderId: sourceId,
        rootBackendId: `training-order-${sourceId}`,
        replacementSequence: 1,
        isPaidRedo: false,
        reason: 'cancelled',
        ...redoExtras,
      },
      ...rest,
    });
  };

  const orders: PatientOrder[] = [
    {
      id: 101,
      backendId: 'training-order-101',
      organisationId,
      patientId: patients[1].id,
      date: daysAgo(1),
      dispensingFee: 0,
      paymentRoute: 'manual',
      payment: {
        status: 'sent',
        route: 'pharmacy',
        amount,
        ref: 'TILL-TRAINING-101',
        sentAt: daysAgo(1),
        paidAt: null,
        manualTender: 'epos-card',
        manualReference: 'TILL-TRAINING-101',
        manualNotes: 'Training example — awaiting pharmacy-managed payment.',
        manualRecordedBy: 'Training workspace',
      },
      prescriptions: [clinicRx(1011, 'draft', {
        curaleafPatientName: patients[1].name,
        curaleafPatientDob: patients[1].dob,
      })],
    },
    {
      id: 102,
      backendId: 'training-order-102',
      organisationId,
      patientId: patients[2].id,
      date: daysAgo(2),
      dispensingFee: 0,
      paymentRoute: 'manual',
      payment: {
        status: 'paid',
        route: 'pharmacy',
        amount,
        ref: 'TILL-TRAINING-102',
        sentAt: daysAgo(2),
        paidAt: daysAgo(2),
        manualTender: 'epos-card',
        manualReference: 'TILL-TRAINING-102',
        manualNotes: 'Training example — paid, waiting for purchase order.',
        manualRecordedBy: 'Training workspace',
      },
      prescriptions: [clinicRx(1021, 'awaiting-approval', {
        curaleafPatientName: patients[2].name,
        curaleafPatientDob: patients[2].dob,
        curaleafPrescriptionState: 'PENDING',
      })],
    },
    {
      id: 103,
      backendId: 'training-order-103',
      organisationId,
      patientId: patients[3].id,
      date: daysAgo(5),
      dispensingFee: 0,
      paymentRoute: 'manual',
      payment: {
        status: 'paid',
        route: 'pharmacy',
        amount,
        ref: 'TILL-TRAINING-103',
        sentAt: daysAgo(5),
        paidAt: daysAgo(5),
        manualTender: 'cash',
        manualReference: 'TILL-TRAINING-103',
        manualNotes: 'Training example — purchase order in transit.',
        manualRecordedBy: 'Training workspace',
      },
      prescriptions: [clinicRx(1031, 'dispatched', {
        curaleafPatientName: patients[3].name,
        curaleafPatientDob: patients[3].dob,
        placed: true,
        placedAt: daysAgo(4),
        poRef: 'PO-TRAINING-103',
        purchaseOrderState: 'PROCESSING',
        dispatchStatus: 'complete',
        trackingNumber: 'TRN-103',
        carrier: 'Training courier',
        fulfilmentLines: [{
          productId: TRAINING_PRODUCT.id,
          ordered: 1,
          requested: 1,
          sent: 1,
          supplierReportedOrdered: 1,
          allocated: 1,
          shipped: 1,
          remaining: 0,
          received: 0,
          collected: 0,
          returned: 0,
          backordered: false,
          quantityMismatch: false,
        }],
      })],
    },
    {
      id: 104,
      backendId: 'training-order-104',
      organisationId,
      patientId: patients[4].id,
      date: daysAgo(8),
      dispensingFee: 0,
      paymentRoute: 'manual',
      payment: {
        status: 'paid',
        route: 'pharmacy',
        amount,
        ref: 'TILL-TRAINING-104',
        sentAt: daysAgo(8),
        paidAt: daysAgo(8),
        manualTender: 'bank-transfer',
        manualReference: 'TILL-TRAINING-104',
        manualNotes: 'Training example — ready for collection.',
        manualRecordedBy: 'Training workspace',
      },
      prescriptions: [clinicRx(1041, 'ready', {
        curaleafPatientName: patients[4].name,
        curaleafPatientDob: patients[4].dob,
        placed: true,
        placedAt: daysAgo(7),
        poRef: 'PO-TRAINING-104',
        purchaseOrderState: 'FULLY_ALLOCATED',
        dispatchStatus: 'complete',
        trackingNumber: 'TRN-104',
        carrier: 'Training courier',
        receivedItems: [{ productId: TRAINING_PRODUCT.id, quantityReceived: 1 }],
        goodsInAt: daysAgo(2),
        goodsInBy: 'Training workspace',
        readyAt: daysAgo(1),
        fulfilmentLines: [{
          productId: TRAINING_PRODUCT.id,
          ordered: 1,
          requested: 1,
          sent: 1,
          supplierReportedOrdered: 1,
          allocated: 1,
          shipped: 1,
          remaining: 0,
          received: 1,
          collected: 0,
          returned: 0,
          backordered: false,
          quantityMismatch: false,
        }],
      })],
    },
    {
      id: 105,
      backendId: 'training-order-105',
      organisationId,
      patientId: patients[5].id,
      date: daysAgo(14),
      dispensingFee: 0,
      paymentRoute: 'manual',
      payment: {
        status: 'paid',
        route: 'pharmacy',
        amount,
        ref: 'TILL-TRAINING-105',
        sentAt: daysAgo(14),
        paidAt: daysAgo(14),
        manualTender: 'epos-card',
        manualReference: 'TILL-TRAINING-105',
        manualNotes: 'Training example — collected.',
        manualRecordedBy: 'Training workspace',
      },
      prescriptions: [clinicRx(1051, 'collected', {
        curaleafPatientName: patients[5].name,
        curaleafPatientDob: patients[5].dob,
        placed: true,
        placedAt: daysAgo(13),
        poRef: 'PO-TRAINING-105',
        purchaseOrderState: 'FULLY_ALLOCATED',
        dispatchStatus: 'complete',
        trackingNumber: 'TRN-105',
        carrier: 'Training courier',
        receivedItems: [{ productId: TRAINING_PRODUCT.id, quantityReceived: 1 }],
        goodsInAt: daysAgo(10),
        goodsInBy: 'Training workspace',
        readyAt: daysAgo(9),
        fulfilmentLines: [{
          productId: TRAINING_PRODUCT.id,
          ordered: 1,
          requested: 1,
          sent: 1,
          supplierReportedOrdered: 1,
          allocated: 1,
          shipped: 1,
          remaining: 0,
          received: 1,
          collected: 1,
          returned: 0,
          backordered: false,
          quantityMismatch: false,
        }],
      })],
    },
    orderShell(111, 'rowan', 3, paid(111, 3, 'Training example — split: one pack dispensed at Curaleaf, one still awaiting allocate.', splitAmount), [namedRx(1111, 'rowan', 'processing', {
      items: [twoPacks],
      placed: true,
      placedAt: daysAgo(3),
      poRef: 'PO-TRAINING-111',
      purchaseOrderState: 'PROCESSING',
      dispatchStatus: 'not_dispatched',
      fulfilmentLines: [line({ ordered: 2, allocated: 1, shipped: 0, received: 0, collected: 0 })],
    })]),
    orderShell(112, 'drew', 4, paid(112, 4, 'Training example — split: first pack with courier, remainder awaiting dispatch.', splitAmount), [namedRx(1121, 'drew', 'dispatched', {
      items: [twoPacks],
      placed: true,
      placedAt: daysAgo(4),
      poRef: 'PO-TRAINING-112',
      purchaseOrderState: 'PROCESSING',
      dispatchStatus: 'partial',
      trackingNumber: 'TRN-112A',
      carrier: 'Training courier',
      fulfilmentLines: [line({ ordered: 2, allocated: 2, shipped: 1, received: 0, collected: 0, remaining: 1 })],
    })]),
    orderShell(113, 'sage', 5, paid(113, 5, 'Training example — split: one pack checked in, one still in transit.', splitAmount), [namedRx(1131, 'sage', 'partially-received', {
      items: [twoPacks],
      placed: true,
      placedAt: daysAgo(5),
      poRef: 'PO-TRAINING-113',
      purchaseOrderState: 'FULLY_ALLOCATED',
      dispatchStatus: 'complete',
      trackingNumber: 'TRN-113A',
      carrier: 'Training courier',
      receivedItems: [{ productId: TRAINING_PRODUCT.id, quantityReceived: 1 }],
      goodsInAt: daysAgo(1),
      goodsInBy: 'Training workspace',
      fulfilmentLines: [line({ ordered: 2, allocated: 2, shipped: 2, received: 1, collected: 0 })],
    })]),
    orderShell(114, 'quinn', 6, paid(114, 6, 'Training example — split: first consignment checked in, remainder awaiting dispatch.', splitAmount), [namedRx(1141, 'quinn', 'partially-received', {
      items: [twoPacks],
      placed: true,
      placedAt: daysAgo(6),
      poRef: 'PO-TRAINING-114',
      purchaseOrderState: 'PROCESSING',
      dispatchStatus: 'partial',
      trackingNumber: 'TRN-114A',
      carrier: 'Training courier',
      receivedItems: [{ productId: TRAINING_PRODUCT.id, quantityReceived: 1 }],
      goodsInAt: daysAgo(2),
      goodsInBy: 'Training workspace',
      fulfilmentLines: [line({ ordered: 2, allocated: 2, shipped: 1, received: 1, collected: 0, remaining: 1 })],
    })]),
    orderShell(115, 'blair', 9, paid(115, 9, 'Training example — split: one pack collected, one still at the pharmacy.', splitAmount), [namedRx(1151, 'blair', 'ready', {
      items: [twoPacks],
      placed: true,
      placedAt: daysAgo(8),
      poRef: 'PO-TRAINING-115',
      purchaseOrderState: 'FULLY_ALLOCATED',
      dispatchStatus: 'complete',
      trackingNumber: 'TRN-115',
      carrier: 'Training courier',
      receivedItems: [{ productId: TRAINING_PRODUCT.id, quantityReceived: 2 }],
      goodsInAt: daysAgo(3),
      goodsInBy: 'Training workspace',
      readyAt: daysAgo(2),
      fulfilmentLines: [line({ ordered: 2, allocated: 2, shipped: 2, received: 2, collected: 1 })],
    })]),
    orderShell(121, 'harper', 1, paid(121, 1, 'Training example — quote review: patient price increased after payment.'), [namedRx(1211, 'harper', 'awaiting-approval')], {
      quoteChecks: [
        { id: 'training-quote-121-pre', phase: 'PRE_PAYMENT', status: 'MATCHED', checkedAt: daysAgo(1).toISOString(), basketFingerprint: 'training-121', patientTotalPence: 8500, wholesaleTotalPence: 4200, shippingPence: 0, stockAvailable: true },
        { id: 'training-quote-121-post', phase: 'POST_PAYMENT', status: 'CHANGED', checkedAt: daysAgo(1).toISOString(), basketFingerprint: 'training-121', comparedWithQuoteCheckId: 'training-quote-121-pre', patientTotalPence: 9500, wholesaleTotalPence: 4200, shippingPence: 0, patientDeltaPence: 1000, stockAvailable: true },
      ],
      activeQuoteCheck: { id: 'training-quote-121-post', phase: 'POST_PAYMENT', status: 'CHANGED', checkedAt: daysAgo(1).toISOString(), basketFingerprint: 'training-121', comparedWithQuoteCheckId: 'training-quote-121-pre', patientTotalPence: 9500, wholesaleTotalPence: 4200, shippingPence: 0, patientDeltaPence: 1000, stockAvailable: true },
      quoteReview: review('required', 'patient_price_changed', [{
        category: 'patient_price',
        field: 'patientPackPrice',
        packId: TRAINING_PRODUCT.id,
        previous: '8500',
        latest: '9500',
      }], quote('95.00', '42.00'), { patientDeltaPence: 1000 }),
    }),
    orderShell(122, 'ellis', 1, paid(122, 1, 'Training example — quote review: patient price dropped after payment.'), [namedRx(1221, 'ellis', 'awaiting-approval')], {
      quoteReview: review('required', 'patient_price_changed', [{
        category: 'patient_price',
        field: 'patientPackPrice',
        packId: TRAINING_PRODUCT.id,
        previous: '8500',
        latest: '7500',
      }], quote('75.00', '42.00'), { patientDeltaPence: -1000 }),
    }),
    orderShell(123, 'indie', 1, paid(123, 1, 'Training example — quote review: Curaleaf reports a line out of stock.'), [namedRx(1231, 'indie', 'awaiting-approval')], {
      quoteReview: review('required', 'out_of_stock', [{
        category: 'stock',
        field: 'inStock',
        packId: TRAINING_PRODUCT.id,
        previous: true,
        latest: false,
      }], quote('85.00', '42.00', false)),
    }),
    orderShell(124, 'marlow', 1, paid(124, 1, 'Training example — quote review: wholesale cost changed after payment.'), [namedRx(1241, 'marlow', 'awaiting-approval')], {
      quoteReview: review('required', 'supplier_cost_changed', [{
        category: 'supplier_cost',
        field: 'wholesalePackPrice',
        packId: TRAINING_PRODUCT.id,
        previous: '4200',
        latest: '4800',
      }], quote('85.00', '48.00')),
    }),
    orderShell(125, 'shiloh', 2, paid(125, 2, 'Training example — quote review: price increase awaiting absorb or cancel.'), [namedRx(1251, 'shiloh', 'awaiting-approval')], {
      quoteReview: review('required', 'patient_price_changed', [{
        category: 'patient_price',
        field: 'patientPackPrice',
        packId: TRAINING_PRODUCT.id,
        previous: '8500',
        latest: '9500',
      }], quote('95.00', '42.00'), { patientDeltaPence: 1000 }),
    }),
    orderShell(126, 'jules', 2, paid(126, 2, 'Training example — quote review: price decrease awaiting absorb or cancel.'), [namedRx(1261, 'jules', 'awaiting-approval')], {
      curaleafPlacement: { route: 'MANUAL_PRESCRIPTION', stage: 'AWAITING_PRESCRIPTION_ACTIVATION', prescriberState: 'VERIFIED', prescriptionState: 'PENDING', attentionReason: 'prescription_activation', nextCheckAt: new Date(Date.now() + 60_000).toISOString(), updatedAt: daysAgo(1).toISOString() },
      quoteReview: review('required', 'patient_price_changed', [{
        category: 'patient_price',
        field: 'patientPackPrice',
        packId: TRAINING_PRODUCT.id,
        previous: '8500',
        latest: '7500',
      }], quote('75.00', '42.00'), { patientDeltaPence: -1000 }),
    }),
    orderShell(131, 'cameron', 8, paid(131, 8, 'Training example — cancelled and refunded, then replaced with a new payment.'), [cancelledRx(1311, 'cameron')], {
      lifecycleStatus: 'cancelled',
      unresolvedReason: 'cancelled',
      redoEligible: false,
      redoneByOrderId: 'training-order-132',
      cancellation: {
        status: 'refund_required',
        reason: 'patient_request',
        note: 'Training example — patient cancelled. Refund completed, then a new paid replacement was created.',
        requestedAt: daysAgo(7).toISOString(),
        requestedBy: 'Training workspace',
        paymentLinkStatus: 'not_applicable',
      },
      refund: {
        id: 'training-refund-131',
        status: 'completed',
        amountPence: Math.round(amount * 100),
        method: 'pharmacy_manual',
        paymentReference: 'TILL-TRAINING-131',
        reason: 'patient_cancelled',
        resolution: 'replace_new_payment',
        requestedAt: daysAgo(7).toISOString(),
        requestedBy: 'Training workspace',
        confirmedAt: daysAgo(6).toISOString(),
        confirmedBy: 'Training workspace',
        externalReference: 'EPOS-REF-131',
      },
    }),
    replacement(132, 131, 'cameron', 5, paid(132, 5, 'Training example — replacement after a completed refund. New payment, not a carry-over.')),
    orderShell(133, 'dana', 7, paid(133, 7, 'Training example — cancelled without refund. Replacement carries the original payment and absorbs a price rise.'), [cancelledRx(1331, 'dana')], {
      lifecycleStatus: 'cancelled',
      unresolvedReason: 'cancelled',
      redoEligible: false,
      redoneByOrderId: 'training-order-134',
      cancellation: {
        status: 'cancelled',
        reason: 'patient_request',
        note: 'Training example — cancelled without refund so the paid amount could be reused.',
        requestedAt: daysAgo(6).toISOString(),
        requestedBy: 'Training workspace',
        paymentLinkStatus: 'not_applicable',
      },
    }),
    replacement(
      134,
      133,
      'dana',
      4,
      paid(134, 4, 'Training example — paid carry-over. Patient price rose £10; pharmacy absorbs the difference.', amount),
      {
        redoContext: { originalOrderId: 133, isPaidRedo: true, reason: 'cancelled', priceResolution: 'absorb' },
        pharmacyContribution: raisedAmount - amount,
        prescriptions: [namedRx(1341, 'dana', 'awaiting-approval', { items: [{ ...pack, retail: raisedAmount }] })],
      },
      { ...pack, retail: raisedAmount },
    ),
    orderShell(135, 'robin', 7, paid(135, 7, 'Training example — cancelled without refund. Replacement reuses the original payment at the same price.'), [cancelledRx(1351, 'robin')], {
      lifecycleStatus: 'cancelled',
      unresolvedReason: 'cancelled',
      redoEligible: false,
      redoneByOrderId: 'training-order-136',
      cancellation: {
        status: 'cancelled',
        reason: 'patient_request',
        note: 'Training example — clean carry-over. Same patient price, no second charge.',
        requestedAt: daysAgo(6).toISOString(),
        requestedBy: 'Training workspace',
        paymentLinkStatus: 'not_applicable',
      },
    }),
    replacement(136, 135, 'robin', 4, paid(136, 4, 'Training example — paid carry-over at the original price. No top-up or refund.'), {
      redoContext: { originalOrderId: 135, isPaidRedo: true, reason: 'cancelled' },
    }),
    orderShell(141, 'finley', 3, paid(141, 3, 'Training example — cancellation started. Call Curaleaf before refunding or replacing.'), [namedRx(1411, 'finley', 'processing', {
      placed: true,
      placedAt: daysAgo(3),
      poRef: 'PO-TRAINING-141',
      purchaseOrderState: 'CREATED',
      curaleafPrescriptionState: 'ACTIVE',
    })], {
      lifecycleStatus: 'cancelled',
      unresolvedReason: 'cancelled',
      cancellation: {
        status: 'curaleaf_contact_required',
        reason: 'patient_request',
        note: 'Training example — HHH cancelled locally. Curaleaf still has a live purchase order.',
        requestedAt: daysAgo(1).toISOString(),
        requestedBy: 'Training workspace',
        paymentLinkStatus: 'not_applicable',
      },
      curaleafCancellation: {
        status: 'contact_required',
        purchaseOrderId: 'PO-TRAINING-141',
        requestedAt: daysAgo(1).toISOString(),
        requestedBy: 'Training workspace',
      },
    }),
    orderShell(142, 'kai', 40, paid(142, 40, 'Training example — 28-day CD expiry. Archive and replace if the patient still needs the medication.'), [namedRx(1421, 'kai', 'awaiting-approval')], {
      lifecycleStatus: 'archived',
      isExpired: true,
      unresolvedReason: 'expired',
      redoEligible: true,
      cycleExpiresAt: daysAgo(12).toISOString(),
    }),
    orderShell(143, 'skyler', 4, paid(143, 4, 'Training example — Curaleaf rejected the quote. Recreate the order.'), [namedRx(1431, 'skyler', 'awaiting-approval')], {
      unresolvedReason: 'rejected',
      redoEligible: true,
      quoteReview: review('recreate_required', 'out_of_stock', [{
        category: 'stock',
        field: 'inStock',
        packId: TRAINING_PRODUCT.id,
        previous: true,
        latest: false,
      }], quote('85.00', '42.00', false)),
    }),
    orderShell(144, 'peyton', 2, paid(144, 2, 'Training example — cancelled remainder with the payment still held. Refund in ePOS, then confirm the reference.'), [cancelledRx(1441, 'peyton', {
      items: [twoPacks],
      fulfilmentLines: [line({ ordered: 2, allocated: 1, shipped: 1, received: 1, collected: 0, remaining: 1, cancelledRemainder: 1, remainingExpected: 0 })],
    })], {
      lifecycleStatus: 'cancelled',
      unresolvedReason: 'cancelled',
      cancellation: {
        status: 'refund_required',
        reason: 'patient_request',
        note: 'Training example — supplier cancelled. Patient refund is still outstanding.',
        requestedAt: daysAgo(1).toISOString(),
        requestedBy: 'Training workspace',
        paymentLinkStatus: 'not_applicable',
      },
      refund: {
        id: 'training-refund-144',
        status: 'pending_confirmation',
        amountPence: Math.round(amount * 100),
        method: 'pharmacy_manual',
        paymentReference: 'TILL-TRAINING-144',
        reason: 'patient_cancelled',
        resolution: 'cancel',
        requestedAt: daysAgo(1).toISOString(),
        requestedBy: 'Training workspace',
      },
    }),
  ];

  const nextRx = Math.max(...orders.flatMap(order => order.prescriptions.map(rx => rx.id)), 0) + 1;
  const nextOrder = Math.max(...orders.map(order => order.id), 0) + 1;

  return {
    crm: patients,
    orders,
    nextIds: { patient: 2000, rx: nextRx, order: nextOrder, submission: 5, invoice: 4072 },
  };
}
